import type {
  DateRangePreset,
  ProgressWindow,
  QuickAccessItem,
  Region,
  ScopeOption,
  StatusKey,
} from "../types/home";

export const DAILY_QUOTES = [
  "Happiness is a choice",
  "You are enough",
  "Dream big, work hard",
  "Smile often",
  "Be the sunshine",
  "Enjoy the little things",
  "Stay positive",
  "Chase your dreams",
  "Kindness is free",
  "Make today amazing",
  "Love more, worry less",
  "Choose joy",
  "The best is yet to come",
  "You’ve got this",
  "Believe in yourself",
  "Shine bright",
  "Every day is a fresh start",
  "Happiness looks good on you",
  "Keep going, keep growing",
  "Celebrate every victory",
  "Spread love everywhere you go",
  "Good vibes only",
  "You are capable of amazing things",
  "Be fearless in pursuit of your dreams",
  "Live, laugh, love",
  "Do more of what makes you happy",
  "Start where you are",
  "Progress, not perfection",
  "Every moment is a gift",
  "Radiate positivity",
  "Focus on the good",
  "Be your own kind of beautiful",
  "Keep your face to the sunshine",
  "Stay hopeful",
  "Smile—it’s contagious",
  "Success is a journey",
  "Be the change you wish to see",
  "Dare to be different",
  "Life is short, make it sweet",
  "You’re stronger than you think",
  "Embrace the journey",
  "Laugh loud, love louder",
  "Take it one step at a time",
  "You are your only limit",
  "Spread your wings and fly",
  "Trust the timing of your life",
  "The sky is the limit",
  "Find joy in the journey",
  "Gratitude changes everything",
  "Be present in all things",
  "The world needs your light",
  "Happiness starts with you",
  "Your vibe attracts your tribe",
  "Keep moving forward",
  "Start each day with a grateful heart",
  "Be unapologetically you",
  "Nothing is impossible",
  "Say yes to new adventures",
  "Breathe. You’ve got this",
  "Do what you love",
  "Dream it, believe it, achieve it",
  "Stay wild, moon child",
  "Celebrate your uniqueness",
  "Great things never come from comfort zones",
  "Be a rainbow in someone else’s cloud",
  "Keep your eyes on the stars",
  "Happiness is homemade",
  "The magic is in you",
  "You’re doing better than you think",
  "Every day is a new beginning",
  "Live life in full bloom",
  "Success starts with believing in yourself",
  "Take time to make your soul happy",
  "Follow your heart",
  "Stay curious",
  "Do good, feel good",
  "Happiness blooms from within",
  "Enjoy every moment",
  "Make today count",
  "Be the reason someone smiles today",
  "Create your own sunshine",
  "Let your dreams take flight",
  "Celebrate your progress",
  "Live with no regrets",
  "Find beauty in the ordinary",
  "Let your heart lead the way",
  "Happiness is a journey, not a destination",
  "Be kind to yourself",
  "Think happy, be happy",
  "Don’t wait for the perfect moment",
  "Keep dreaming big",
  "Your smile is your superpower",
  "Life is what you make it",
  "You have what it takes",
  "Choose happiness every day",
  "Be bold, be brave",
  "Stay golden",
  "Cheers and happy activities",
];

export const STATUS_KEYS: StatusKey[] = [
  "Bidding",
  "Pending",
  "Ordered",
  "Pass",
  "Failed",
];

export const DATE_RANGE_PRESETS: DateRangePreset[] = [
  "Today",
  "Yesterday",
  "This Week",
  "This Month",
  "This Quarter",
  "This Year",
  "Last 7 Days",
  "Last 30 Days",
  "Last Month",
];

export const SCOPE_OPTIONS: ScopeOption[] = [
  { value: "Your", label: "Your" },
  { value: "Total", label: "Total" },
];

export const PROGRESS_WINDOWS: ProgressWindow[] = [7, 30, 90];

export const QUICK_ACCESS: Record<Region, QuickAccessItem[]> = {
  KR: [
    {
      mode: "create",
      title: "Create RFQ",
      description: "Calculate and generate RFQ",
      icon: "plus",
    },
    {
      mode: "draft",
      title: "Drafts",
      description: "Keep editing all saved RFQ drafts",
      icon: "sticky",
    },
    {
      mode: "list",
      title: "RFQ List",
      description: "Access and review all RFQs",
      icon: "file",
    },
  ],
  OS: [
    {
      mode: "create",
      title: "Create RFQ",
      description: "Calculate and generate RFQ",
      icon: "plus",
    },
    {
      mode: "draft",
      title: "Drafts",
      description: "Keep editing all saved RFQ drafts",
      icon: "sticky",
    },
    {
      mode: "list",
      title: "RFQ List",
      description: "Access and review all RFQs",
      icon: "file",
    },
    {
      mode: "vendor",
      title: "Vendor List",
      description: "View details of all vendors",
      icon: "people",
    },
  ],
};
